# Generated by Django 4.1.2 on 2022-10-12 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('temoignage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='temoignage',
            options={'verbose_name': 'temoignage', 'verbose_name_plural': 'temoignages'},
        ),
    ]
