# Generated by Django 4.1.2 on 2022-10-12 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0002_flexpage_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flexpage',
            old_name='text',
            new_name='apropos_text',
        ),
    ]
